name: Deploy Streamlit App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test app
      run: |
        python -c "import streamlit; print('Streamlit installed successfully')"
        python -c "import tensorflow; print('TensorFlow installed successfully')"
    
    - name: Deploy to Streamlit Cloud
      run: |
        echo "App ready for deployment to Streamlit Cloud"
        echo "Visit https://share.streamlit.io to deploy this app"
